baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Kamelija Arnautova"
 
  # staticPath: ""  # The path to serve the static files from


  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hello, my name is"
    title: "Kamelija Arnautova."
    image: /images/DSC_2509 - 1.jpg
  

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
     I'm a developer with experience in building responsive and user-friendly websites and web applications. Web development has always been my passion, thus I make sure to always deliver the best results.
      My main focus are on static site generation using Gatsby/React.js, Hugo, Jekyll, etc.
      Hence, I have good skills and experiences in React.js, HTML, SASS/SCSS, CSS, Javascript.
      And I have good working experience with PHP and building databases with SQL for the backend.
      Also, I have much familiar with headless CMS such as Contentful CMS, Netlify CMS, Strapi, etc.
      I am a quick-learner and I can easily learn a new and unfamiliar enviroment/system.
      I love communicating and understanding your visions and create what you need.
      Let's keep in touch!
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Gatsby/React.js"
        - "Hugo"
        - "Jekyll"
        - "PHP"
        - "MySql"
        - "Sql"
        - "HTML"
        - "SASS/SCSS"
        - "CSS"
        - "JavaScript"
        


  # Education
  education:
    enable: true
    # index: true
    items:
  
      - title: "Computer engineering and technolog "
        school:
          name: "University of “Goce Delcev”, Shtip"
         
        date: "2017 - 2021"
          
      

  

  # projects
  projects:
    enable: true
    items:
      - title: Cart
        content: Food menu with adding to cart. 
        image: /images/cart.jpg
        links:
          - icon: fab fa-github
            url: https://github.com/kamelija6/foodmine-course/tree/master
    

      - title: Navbar
        content: Navigation bar.
        image: /images/navbar.jpg
        links:
          - icon: fab fa-github
            url: https://github.com/kamelija6/navbar-app/tree/master

      - title: Todo list
        content: An ToDo list with adding and removing todos.
        image: /images/todo.jpg
        links:
          - icon: fab fa-github
            url: https://github.com/kamelija6/Angular-Todo/tree/master

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: kamelija.arnautova7@gmail.com
    btnName: Mail me

  footer:
  